displayName=Inventory Item Counter
author=MFDumile
description=Shows an overlay that counts the items on your inventory. Useful for activities where specific amount of items are required.
tags=items,inventory,count,counter,item counter, inventory counter
version=
plugins=com.example.InventoryItemCounterPlugin
build=standard